#!/usr/bin/env php
<?php

declare(strict_types=1);

use S\Foundation\Cli\Application;
use S\Foundation\Cli\Context;

require_once __DIR__.'/bootstrap.php';

$app = new Application(Context::global($argc, $argv));

$app->on('hello [name]', fn (Context $context) => 'Hello '.$context->getAttribute('name', 'World').'!'.PHP_EOL);

$app->run();
