#!/usr/bin/env php
<?php

declare(strict_types=1);

use S\Foundation\Cli\Context;
use S\Foundation\Cli\Application;

require_once __DIR__.'/bootstrap.php';

$context = Context::global($argc, $argv);

$app = new Application($context);

$app->on('hello [name]', fn() => 'Welcome to S!'.PHP_EOL);

$app->run();
